(() => {
'use strict';
const REPO='maxskill115/DaiMinhChu-Asset';
const BRANCH='main';
const RAW=`https://raw.githubusercontent.com/${REPO}/${BRANCH}/`;
const $=id=>document.getElementById(id);
const ui={canvas:$('sceneCanvas'),viewer:$('viewer'),list:$('effectList'),search:$('searchInput'),count:$('effectCount'),catalogSource:$('catalogSource'),currentName:$('currentName'),currentMeta:$('currentMeta'),loading:$('loading'),loadingTitle:$('loadingTitle'),loadingDetail:$('loadingDetail'),empty:$('emptyState'),error:$('errorBox'),status:$('statusText'),play:$('playPauseBtn'),restart:$('restartBtn'),focus:$('focusBtn'),speed:$('speedRange'),speedValue:$('speedValue'),mode:$('displayMode'),blend:$('blendSelect'),transparent:$('transparentToggle'),depthWrite:$('depthWriteToggle'),autoRotate:$('autoRotateToggle'),gridToggle:$('gridToggle'),fps:$('fps'),layerCount:$('layerCount'),meshCount:$('meshCount'),animCount:$('animCount')};

const seed={effects:[
{id:'am-nhien-tieu-hon-chuong',name:'AmNhienTieuHonChuong',label:'Âm Nhiên Tiêu Hồn Chưởng',defaultMode:'composite',layers:[
['AmNhienTieuHonChuong_01','Skills_C12_2.png'],['AmNhienTieuHonChuong_02','Skills_C12_2.png'],['AmNhienTieuHonChuong_03','Skills_C12_2.png'],['AmNhienTieuHonChuong_04','Skills_C12_1.png'],['AmNhienTieuHonChuong_05','Skills_C12_2.png']].map(([name,tex])=>({name,obj:`Tài Nguyên Giải nén/Mesh/${name}.obj`,texture:`Tài Nguyên Giải nén/Animator/${name}/${tex}`}))},
{id:'attack',name:'Attack',label:'Attack',defaultMode:'composite',layers:Array.from({length:6},(_,i)=>{const name=`Attack_${String(i+1).padStart(2,'0')}`;return{name,obj:`Tài Nguyên Giải nén/Mesh/${name}.obj`,texture:`Tài Nguyên Giải nén/Animator/${name}/Skills_C34_1.png`}})}
]};

const ctx=ui.canvas.getContext('2d',{alpha:false,desynchronized:true});
let catalog=[],current=null,layers=[],token=0,playing=true,seqIndex=0,seqTime=0,zoom=1,panX=0,panY=0,drag=false,lastX=0,lastY=0,startedAt=performance.now(),lastFrame=performance.now(),frames=0,fpsAt=performance.now();
const imageCache=new Map();

const enc=p=>p.split('/').map(encodeURIComponent).join('/');
const raw=p=>RAW+enc(p);
const relative=p=>'./'+enc(p);
const primaryUrl=p=>(location.protocol==='http:'||location.protocol==='https:')?relative(p):raw(p);
const urls=p=>{const a=primaryUrl(p),b=raw(p);return a===b?[a]:[a,b]};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const human=s=>String(s).replaceAll('_',' ').replace(/([a-z0-9])([A-Z])/g,'$1 $2');

function message(t){ui.status.textContent=t}
function error(t=''){ui.error.textContent=t;ui.error.classList.toggle('hidden',!t)}
function loading(show,title='Đang tải…',detail=''){ui.loading.classList.toggle('hidden',!show);ui.loadingTitle.textContent=title;ui.loadingDetail.textContent=detail}
function normalize(data){if(!data||!Array.isArray(data.effects))throw new Error('manifest không hợp lệ');return data.effects.filter(x=>Array.isArray(x.layers)&&x.layers.length).map(x=>({...x,id:x.id||x.name,label:x.label||human(x.name),defaultMode:x.defaultMode||'composite'}))}
function visibleCatalog(){const q=ui.search.value.trim().toLowerCase();return q?catalog.filter(x=>`${x.label} ${x.name}`.toLowerCase().includes(q)):catalog}
function renderCatalog(){const items=visibleCatalog();ui.count.textContent=items.length;ui.list.innerHTML='';if(!items.length){ui.list.innerHTML='<div class="catalog-empty">Không có effect khớp tìm kiếm.</div>';return}for(const item of items){const b=document.createElement('button');b.className='effect-item'+(current?.id===item.id?' active':'');b.innerHTML=`<span class="icon">✦</span><span><strong>${esc(item.label)}</strong><small>${item.layers.length} layer · ${esc(item.name)}</small></span><em>FX</em>`;b.onclick=()=>loadEffect(item);ui.list.appendChild(b)}}

async function fetchText(path){let last;for(const u of urls(path)){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}catch(e){last=e}}throw last||new Error('fetch thất bại')}
function loadImage(path){if(imageCache.has(path))return imageCache.get(path);const p=new Promise(async(resolve,reject)=>{let last;for(const u of urls(path)){try{const img=new Image();img.crossOrigin='anonymous';const done=new Promise((res,rej)=>{img.onload=()=>res(img);img.onerror=()=>rej(new Error(`Không tải được ảnh: ${u}`))});img.src=u;resolve(await done);return}catch(e){last=e}}reject(last||new Error('Không tải được texture'))});imageCache.set(path,p);return p}

function parseObj(text){const vs=[],vts=[],tris=[];for(const line of text.split(/\r?\n/)){const a=line.trim().split(/\s+/);if(a[0]==='v'&&a.length>=3){vs.push([+a[1],+a[2],+(a[3]||0)])}else if(a[0]==='vt'&&a.length>=3){vts.push([+a[1],+a[2]])}else if(a[0]==='f'&&a.length>=4){const refs=a.slice(1).map(x=>{const q=x.split('/');return{v:parseInt(q[0],10)-1,vt:q[1]?parseInt(q[1],10)-1:-1}});for(let i=1;i<refs.length-1;i++)tris.push([refs[0],refs[i],refs[i+1]])}}if(!vs.length||!vts.length||!tris.length)throw new Error('OBJ thiếu vertex/UV/face');const xs=vs.map(v=>v[0]),ys=vs.map(v=>v[1]);return{vs,vts,tris,width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys),vertices:vs.length,uvs:vts.length,triangles:tris.length}}

async function loadLayer(meta,my){const [objText,img]=await Promise.all([fetchText(meta.obj),loadImage(meta.texture)]);if(my!==token)return null;const mesh=parseObj(objText);return{...meta,mesh,img}}

async function loadCatalog(){loading(true,'Đang đọc effect…','effects-manifest.json');error('');let data;try{const r=await fetch('./effects-manifest.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();catalog=normalize(data);ui.catalogSource.textContent=`Canvas2D · manifest tĩnh · ${catalog.length} nhóm`}catch(e){console.warn('manifest fallback',e);catalog=normalize(seed);ui.catalogSource.textContent=`Canvas2D · fallback nhúng sẵn · ${catalog.length} nhóm`}renderCatalog();loading(false);message(`Sẵn sàng: ${catalog.length} nhóm effect. Renderer không phụ thuộc CDN.`);if(catalog[0])loadEffect(catalog[0])}

async function loadEffect(effect){const my=++token;current=effect;layers=[];seqIndex=0;seqTime=0;zoom=1;panX=panY=0;renderCatalog();error('');ui.empty.classList.add('hidden');ui.currentName.textContent=effect.label;ui.currentMeta.textContent=`${effect.layers.length} layer · Canvas2D atlas renderer`;ui.mode.value=effect.defaultMode||'composite';loading(true,`Đang dựng ${effect.label}`,'Đọc OBJ + PNG atlas…');message(`Đang tải ${effect.layers.length} layer…`);let failed=[];for(let i=0;i<effect.layers.length;i++){const m=effect.layers[i];ui.loadingDetail.textContent=`${i+1}/${effect.layers.length} · ${m.name}`;try{const x=await loadLayer(m,my);if(my!==token)return;if(x)layers.push(x)}catch(e){console.error(m.name,e);failed.push(`${m.name}: ${e.message}`)}}if(my!==token)return;ui.layerCount.textContent=layers.length;ui.meshCount.textContent=layers.length;ui.animCount.textContent='0';loading(false);if(!layers.length){error(`Không tải được layer nào. ${failed.join(' | ')}`);message('Load effect thất bại — xem lỗi màu đỏ.');return}if(failed.length)error(`Có ${failed.length} layer lỗi: ${failed.join(' | ')}`);ui.currentMeta.textContent=`${layers.length}/${effect.layers.length} layer · OBJ UV + PNG atlas`;message(`Đã dựng ${effect.label}: ${layers.length} layer. Đây là preview texture/mesh; animation gốc sẽ reverse ở bước sau.`);restart()}

function resize(){const r=ui.viewer.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(ui.canvas.width!==w||ui.canvas.height!==h){ui.canvas.width=w;ui.canvas.height=h;ui.canvas.style.width=r.width+'px';ui.canvas.style.height=r.height+'px'}}
function drawGrid(w,h,dpr){ctx.save();ctx.strokeStyle='rgba(120,150,190,.10)';ctx.lineWidth=dpr;const step=50*dpr;for(let x=w/2%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=h/2%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
function maxMeshDim(){let m=.01;for(const l of layers)m=Math.max(m,l.mesh.width,l.mesh.height);return m}
function blendMode(){return ui.blend.value==='multiply'?'multiply':ui.blend.value==='normal'?'source-over':'lighter'}
function affine(src,dst){const [p0,p1,p2]=src,[q0,q1,q2]=dst,x0=p0[0],y0=p0[1],x1=p1[0],y1=p1[1],x2=p2[0],y2=p2[1],den=x0*(y1-y2)+x1*(y2-y0)+x2*(y0-y1);if(Math.abs(den)<1e-8)return null;const coeff=vals=>{const [z0,z1,z2]=vals;return[(z0*(y1-y2)+z1*(y2-y0)+z2*(y0-y1))/den,(z0*(x2-x1)+z1*(x0-x2)+z2*(x1-x0))/den,(z0*(x1*y2-x2*y1)+z1*(x2*y0-x0*y2)+z2*(x0*y1-x1*y0))/den]};const X=coeff([q0[0],q1[0],q2[0]]),Y=coeff([q0[1],q1[1],q2[1]]);return[X[0],Y[0],X[1],Y[1],X[2],Y[2]]}
function drawTexturedTriangle(img,src,dst){const t=affine(src,dst);if(!t)return;ctx.save();ctx.beginPath();ctx.moveTo(dst[0][0],dst[0][1]);ctx.lineTo(dst[1][0],dst[1][1]);ctx.lineTo(dst[2][0],dst[2][1]);ctx.closePath();ctx.clip();ctx.transform(...t);ctx.drawImage(img,0,0);ctx.restore()}
function drawLayer(l,base,t,i){const m=l.mesh,img=l.img,pulse=playing?1+Math.sin(t*3+i*.9)*.015:1,s=base*pulse;ctx.save();ctx.globalAlpha=ui.transparent.checked?(0.92+0.08*Math.sin(t*2+i)):1;for(const tri of m.tris){const src=[],dst=[];let ok=true;for(const r of tri){const v=m.vs[r.v],uv=m.vts[r.vt];if(!v||!uv){ok=false;break}src.push([uv[0]*img.naturalWidth,(1-uv[1])*img.naturalHeight]);dst.push([v[0]*s,-v[1]*s])}if(ok)drawTexturedTriangle(img,src,dst)}ctx.restore()}
function render(now){resize();const w=ui.canvas.width,h=ui.canvas.height,dpr=Math.min(devicePixelRatio||1,2);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;const g=ctx.createRadialGradient(w*.5,h*.48,0,w*.5,h*.48,Math.max(w,h)*.7);g.addColorStop(0,'#0d1524');g.addColorStop(1,'#05070c');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(ui.gridToggle.checked)drawGrid(w,h,dpr);if(!layers.length)return;const mode=ui.mode.value,base=Math.min(w,h)*.58/maxMeshDim()*zoom,t=(now-startedAt)/1000;ctx.save();ctx.translate(w/2+panX*dpr,h/2+panY*dpr);if(ui.autoRotate.checked&&playing)ctx.rotate(t*.35);ctx.globalCompositeOperation=blendMode();for(let i=0;i<layers.length;i++){if(mode==='sequence'&&i!==seqIndex)continue;drawLayer(layers[i],base,t,i)}ctx.restore()}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-lastFrame)/1000,.1);lastFrame=now;if(playing&&ui.mode.value==='sequence'&&layers.length>1){seqTime+=dt*Math.max(0,+ui.speed.value);if(seqTime>=.12){seqTime%=.12;seqIndex=(seqIndex+1)%layers.length}}render(now);frames++;const span=now-fpsAt;if(span>=700){ui.fps.textContent=Math.round(frames*1000/span);frames=0;fpsAt=now}}
function togglePlay(){playing=!playing;ui.play.textContent=playing?'⏸ Pause':'▶ Play';message(playing?'Effect đang chạy.':'Effect đã tạm dừng.')}
function restart(){startedAt=performance.now();seqIndex=0;seqTime=0;playing=true;ui.play.textContent='⏸ Pause';message(current?`Đã chạy lại ${current.label}.`:'Sẵn sàng.')}
function focus(){zoom=1;panX=panY=0;message('Đã đưa effect về giữa màn hình.')}

ui.search.addEventListener('input',renderCatalog);ui.play.onclick=togglePlay;ui.restart.onclick=restart;ui.focus.onclick=focus;ui.speed.oninput=()=>ui.speedValue.textContent=`${Number(ui.speed.value).toFixed(2)}×`;ui.mode.onchange=()=>{seqIndex=0;seqTime=0};ui.blend.onchange=()=>{};ui.depthWrite.disabled=true;ui.depthWrite.title='Canvas2D không dùng depth buffer';window.addEventListener('resize',resize);ui.canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.15,Math.min(8,zoom*Math.exp(-e.deltaY*.001)));},{passive:false});ui.canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;ui.canvas.setPointerCapture?.(e.pointerId)});ui.canvas.addEventListener('pointermove',e=>{if(!drag)return;panX+=e.clientX-lastX;panY+=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY});ui.canvas.addEventListener('pointerup',()=>drag=false);ui.canvas.addEventListener('pointercancel',()=>drag=false);

window.addEventListener('error',e=>{error(`JavaScript error: ${e.message}`);message('Có lỗi JavaScript — xem khung đỏ.')});window.addEventListener('unhandledrejection',e=>{error(`Promise error: ${e.reason?.message||e.reason}`);message('Có lỗi khi tải asset — xem khung đỏ.')});
resize();requestAnimationFrame(animate);loadCatalog();
})();
